# Sampled label consistency

This notebook reads the sampled-label export from `data/labels_sampled/`, merges it with the original labels in `data/labels.jsonl`, and measures agreement on the 1-4 execution score using Cohen's weighted kappa.

In [6]:
import json
from pathlib import Path

import pandas as pd
from IPython.display import display
from sklearn.metrics import cohen_kappa_score

PROJECT_ROOT = Path("..").resolve()
DATA_DIR = PROJECT_ROOT / "data"
LABELS_SAMPLED_DIR = DATA_DIR / "labels_sampled"
LABELS_PATH = DATA_DIR / "labels.jsonl"

pd.set_option("display.max_colwidth", 120)

In [7]:
def extract_first_choice(results, result_type, value_key):
    for result in results:
        if result.get("type") != result_type:
            continue
        value = result.get("value", {}).get(value_key)
        if isinstance(value, list):
            return value[0] if value else None
        return value
    return None


sampled_rows = []
for path in sorted(LABELS_SAMPLED_DIR.iterdir()):
    row = json.loads(path.read_text())
    results = row.get("result", [])
    video_uri = row.get("task", {}).get("data", {}).get("video")
    clip_name = Path(video_uri.split("://", 1)[-1]).name if video_uri else None
    sampled_rows.append(
        {
            "sampled_export_id": row.get("id"),
            "sampled_task_id": row.get("task", {}).get("id"),
            "clip_name": clip_name,
            "sampled_video_uri": video_uri,
            "sampled_created_at": row.get("created_at"),
            "sampled_completed_by": row.get("completed_by", {}).get("email"),
            "sampled_trick": extract_first_choice(results, "choices", "choices"),
            "sampled_score": extract_first_choice(results, "rating", "rating"),
        }
    )

sampled_df = pd.DataFrame(sampled_rows)
sampled_df.head()

,sampled_export_id,sampled_task_id,clip_name,sampled_video_uri,sampled_created_at,sampled_completed_by,sampled_trick,sampled_score
0,1651,10288,25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,s3://aitraf-test/clips/25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,2026-04-20T12:30:25.472229Z,henrikasgir@gmail.com,mizou,4
1,1652,10289,25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,s3://aitraf-test/clips/25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,2026-04-20T12:30:37.324233Z,henrikasgir@gmail.com,None,2
2,1653,10290,25-10-31 19-54-19 5689-00.11.10.367-00.11.15.259-seg20.mp4,s3://aitraf-test/clips/25-10-31 19-54-19 5689-00.11.10.367-00.11.15.259-seg20.mp4,2026-04-20T12:31:54.846706Z,henrikasgir@gmail.com,None,2
3,1654,10291,25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,s3://aitraf-test/clips/25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,2026-04-20T12:32:06.785456Z,henrikasgir@gmail.com,None,2
4,1655,10292,25-11-02 19-14-55 5695-00.00.12.033-00.00.16.478-seg02.mp4,s3://aitraf-test/clips/25-11-02 19-14-55 5695-00.00.12.033-00.00.16.478-seg02.mp4,2026-04-20T12:32:14.989682Z,henrikasgir@gmail.com,None,2

In [8]:
original_df = pd.read_json(LABELS_PATH, lines=True)
original_df["clip_name"] = original_df["video"].map(lambda uri: Path(uri).name)
original_df = original_df.rename(
    columns={
        "video": "original_video_uri",
        "trick": "original_trick",
        "execution_score": "original_score",
        "created_at": "original_created_at",
        "updated_at": "original_updated_at",
        "annotator": "original_annotator",
        "annotation_id": "original_annotation_id",
    }
)

merged_df = sampled_df.merge(
    original_df[
        [
            "clip_name",
            "original_video_uri",
            "original_trick",
            "original_score",
            "original_explanation",
            "original_created_at",
            "original_updated_at",
            "original_annotator",
            "original_annotation_id",
            "person",
            "key_foot",
        ]
    ],
    on="clip_name",
    how="left",
)

merged_df["score_delta"] = merged_df["sampled_score"] - merged_df["original_score"]
merged_df["absolute_score_delta"] = merged_df["score_delta"].abs()
merged_df["exact_match"] = merged_df["sampled_score"] == merged_df["original_score"]

print(f"Sampled export rows: {len(sampled_df)}")
print(f"Matched original labels: {merged_df['original_score'].notna().sum()}")
print(f"Sampled rows with trick labels present: {merged_df['sampled_trick'].notna().sum()}")

merged_df.head()

Sampled export rows: 100
Matched original labels: 100
Sampled rows with trick labels present: 1

,sampled_export_id,sampled_task_id,clip_name,sampled_video_uri,sampled_created_at,sampled_completed_by,sampled_trick,sampled_score,original_video_uri,original_trick,...,original_explanation,original_created_at,original_updated_at,original_annotator,original_annotation_id,person,key_foot,score_delta,absolute_score_delta,exact_match
0,1651,10288,25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,s3://aitraf-test/clips/25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,2026-04-20T12:30:25.472229Z,henrikasgir@gmail.com,mizou,4,s3://aitraf/clips/25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,mizou,...,"Body position on point, but too slow and short",2025-11-09 20:54:12.448141+00:00,2026-01-07 20:20:55.476505+00:00,1,161,Henrikas,right,1,1,False
1,1652,10289,25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,s3://aitraf-test/clips/25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,2026-04-20T12:30:37.324233Z,henrikasgir@gmail.com,None,2,s3://aitraf/clips/25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,top-soul,...,"Position really good, just way too short",2025-11-09 20:54:46.021757+00:00,2026-01-07 14:53:41.775343+00:00,1,164,Max,right,-1,1,False
2,1653,10290,25-10-31 19-54-19 5689-00.11.10.367-00.11.15.259-seg20.mp4,s3://aitraf-test/clips/25-10-31 19-54-19 5689-00.11.10.367-00.11.15.259-seg20.mp4,2026-04-20T12:31:54.846706Z,henrikasgir@gmail.com,None,2,s3://aitraf/clips/25-10-31 19-54-19 5689-00.11.10.367-00.11.15.259-seg20.mp4,ao-soul,...,Very short,2025-11-09 21:00:21.062153+00:00,2026-01-07 20:02:32.656282+00:00,1,190,Max,right,0,0,True
3,1654,10291,25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,s3://aitraf-test/clips/25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,2026-04-20T12:32:06.785456Z,henrikasgir@gmail.com,None,2,s3://aitraf/clips/25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,fs-savanah,...,"Way too short, but form looks confident",2025-11-09 21:01:03.729921+00:00,2026-01-07 20:01:48.924991+00:00,1,192,Henrikas,right,-1,1,False
4,1655,10292,25-11-02 19-14-55 5695-00.00.12.033-00.00.16.478-seg02.mp4,s3://aitraf-test/clips/25-11-02 19-14-55 5695-00.00.12.033-00.00.16.478-seg02.mp4,2026-04-20T12:32:14.989682Z,henrikasgir@gmail.com,None,2,s3://aitraf/clips/25-11-02 19-14-55 5695-00.00.12.033-00.00.16.478-seg02.mp4,fs-royale,...,"Too short, form looks a bit awkward too",2025-11-09 21:01:37.696959+00:00,2026-01-07 20:01:06.403042+00:00,1,194,Romka,left,0,0,True

In [9]:
agreement_df = merged_df.dropna(subset=["sampled_score", "original_score"]).copy()
agreement_df[["sampled_score", "original_score"]] = agreement_df[["sampled_score", "original_score"]].astype(int)

dummy_mode_class = int(agreement_df["original_score"].mode().iloc[0])
agreement_df["dummy_score"] = dummy_mode_class

# Quadratic weights are the primary agreement metric because 1-4 stars are ordinal.
summary_df = pd.DataFrame(
    [
        {"metric": "sampled_export_rows", "value": len(sampled_df)},
        {"metric": "matched_rows", "value": len(agreement_df)},
        {"metric": "dummy_mode_class", "value": dummy_mode_class},
        {"metric": "exact_agreement", "value": float((agreement_df["sampled_score"] == agreement_df["original_score"]).mean())},
        {"metric": "mean_absolute_score_delta", "value": float(agreement_df["absolute_score_delta"].mean())},
        {"metric": "dummy_mae_vs_original", "value": float((agreement_df["original_score"] - agreement_df["dummy_score"]).abs().mean())},
        {"metric": "dummy_mae_vs_sampled", "value": float((agreement_df["sampled_score"] - agreement_df["dummy_score"]).abs().mean())},
        {"metric": "cohen_kappa_unweighted", "value": float(cohen_kappa_score(agreement_df["original_score"], agreement_df["sampled_score"]))},
        {"metric": "cohen_kappa_weighted_linear", "value": float(cohen_kappa_score(agreement_df["original_score"], agreement_df["sampled_score"], weights="linear"))},
        {"metric": "cohen_kappa_weighted_quadratic", "value": float(cohen_kappa_score(agreement_df["original_score"], agreement_df["sampled_score"], weights="quadratic"))},
        {"metric": "dummy_qwk_vs_original", "value": float(cohen_kappa_score(agreement_df["original_score"], agreement_df["dummy_score"], weights="quadratic"))},
        {"metric": "dummy_qwk_vs_sampled", "value": float(cohen_kappa_score(agreement_df["sampled_score"], agreement_df["dummy_score"], weights="quadratic"))},
    ]
)

score_confusion_df = pd.crosstab(
    agreement_df["original_score"],
    agreement_df["sampled_score"],
    rownames=["original_score"],
    colnames=["sampled_score"],
    margins=True,
)

score_delta_df = (
    agreement_df["score_delta"].value_counts().sort_index().rename_axis("score_delta").to_frame("count")
)

score_distribution_df = pd.DataFrame({"score": [1, 2, 3, 4]})
score_distribution_df["original_count"] = score_distribution_df["score"].map(
    agreement_df["original_score"].value_counts()
).fillna(0).astype(int)
score_distribution_df["sampled_count"] = score_distribution_df["score"].map(
    agreement_df["sampled_score"].value_counts()
).fillna(0).astype(int)
score_distribution_df["original_pct"] = (
    score_distribution_df["original_count"] / len(agreement_df)
).round(4)
score_distribution_df["sampled_pct"] = (
    score_distribution_df["sampled_count"] / len(agreement_df)
).round(4)

display(summary_df)
display(score_distribution_df)
display(score_confusion_df)
display(score_delta_df)

                            metric       value
0              sampled_export_rows  100.000000
1                     matched_rows  100.000000
2                 dummy_mode_class    3.000000
3                  exact_agreement    0.640000
4        mean_absolute_score_delta    0.370000
5            dummy_mae_vs_original    0.760000
6             dummy_mae_vs_sampled    0.910000
7           cohen_kappa_unweighted    0.513448
8      cohen_kappa_weighted_linear    0.668161
9   cohen_kappa_weighted_quadratic    0.805039
10           dummy_qwk_vs_original    0.000000
11            dummy_qwk_vs_sampled    0.000000

   score  original_count  sampled_count  original_pct  sampled_pct
0      1              13             10          0.13         0.10
1      2              24             39          0.24         0.39
2      3              37             19          0.37         0.19
3      4              26             32          0.26         0.32

sampled_score    1   2   3   4  All
original_score
1                9   4   0   0   13
2                1  20   3   0   24
3                0  14  13  10   37
4                0   1   3  22   26
All             10  39  19  32  100

             count
score_delta
-2               1
-1              18
 0              64
 1              17

In [10]:
disagreements_df = merged_df[~merged_df["exact_match"]].copy()
disagreements_df = disagreements_df.sort_values(
    ["absolute_score_delta", "clip_name"],
    ascending=[False, True],
)

display(
    disagreements_df[
        [
            "clip_name",
            "person",
            "original_trick",
            "original_score",
            "sampled_score",
            "score_delta",
            "original_explanation",
        ]
    ]
)

,clip_name,person,original_trick,original_score,sampled_score,score_delta,original_explanation
44,25-11-15 19-11-43 5734-00.09.24.041-00.09.29.406-seg13.mp4,Henrikas,bs-royale,4,2,-2,Not perfect but clean enough. Body position should be lower
0,25-10-31 19-46-26 5688-00.02.44.697-00.02.49.504-seg09.mp4,Henrikas,mizou,3,4,1,"Body position on point, but too slow and short"
1,25-10-31 19-46-26 5688-00.04.33.222-00.04.38.667-seg12.mp4,Max,top-soul,3,2,-1,"Position really good, just way too short"
3,25-10-31 19-54-19 5689-00.13.09.900-00.13.15.589-seg24.mp4,Henrikas,fs-savanah,3,2,-1,"Way too short, but form looks confident"
6,25-11-02 19-14-55 5695-00.02.27.610-00.02.32.507-seg11.mp4,Justas,mizou,3,4,1,"A bit too short, but body position on point"
7,25-11-02 19-14-55 5695-00.09.06.529-00.09.10.447-seg36.mp4,Rytis,bs-royale,2,3,1,feet position just not in place in my opinion. Unclear if its a royale or backside
8,25-11-02 19-14-55 5695-00.12.29.692-00.12.33.943-seg61.mp4,Romka,fs-royale,3,4,1,"full box, good speed, sketchy at the end"
10,25-11-07 15-47-00 5699-00.00.39.770-00.00.45.637-seg02.mp4,Max,soul,3,2,-1,"Short, but looks controlled overall"
11,25-11-07 15-47-00 5699-00.00.49.152-00.00.53.874-seg03.mp4,Henrikas,soul,2,3,1,Too short and something about it looks off
13,25-11-07 15-47-00 5699-00.05.10.822-00.05.14.479-seg08.mp4,Max,soul,3,2,-1,"Too short, but great otherwise"
16,25-11-07 15-47-00 5699-00.12.39.528-00.12.44.702-seg21.mp4,Henrikas,top-soul,4,3,-1,"Body position should be lower, but great overall"
21,25-11-10 20-27-54 5708-00.02.55.881-00.03.02.075-seg08.mp4,Henrikas,fs-royale,3,4,1,"Looks really controlled, just a bit shy for length for being great"
24,25-11-10 20-36-17 5709-00.03.41.113-00.03.45.665-seg11.mp4,Henrikas,mizou,3,2,-1,"In control, just too short and slow"
26,25-11-13 20-29-29 5726-00.01.15.659-00.01.20.388-seg02.mp4,Henrikas,soul,1,2,1,short & awkward
31,25-11-13 20-34-37 5727-00.14.48.955-00.14.53.951-seg19.mp4,Henrikas,fs-royale,3,4,1,"full length, but need lower body position for this trick."
36,25-11-15 18-42-16 5731-00.02.01.860-00.02.07.116-seg03.mp4,Henrikas,mizou,3,2,-1,"Clearly too slow, but the execution looks great"
40,25-11-15 18-42-16 5731-00.14.10.444-00.14.15.634-seg27.mp4,Max,fs-royale,3,4,1,A bit too shy of length in the end. But great body position.
42,25-11-15 18-42-16 5731-00.18.16.571-00.18.22.097-seg34.mp4,Henrikas,ao-soul,3,2,-1,A bit unstable balance. But great length.
46,25-11-15 19-11-43 5734-00.13.26.792-00.13.31.606-seg19.mp4,Henrikas,bs-royale,3,4,1,"Great, but landing seems awkward/forced"
48,25-11-17 21-01-19 5741-00.00.27.486-00.00.31.851-seg02.mp4,Henrikas,soul,3,4,1,Bit too short for being really great
52,25-11-17 21-01-19 5741-00.10.21.413-00.10.24.437-seg27.mp4,Vilius,fs-royale,2,1,-1,"form good, but landing really sketchy"
76,25-12-01 20-52-05 5968-00.00.05.247-00.00.09.829-seg01.mp4,Henrikas,mizou,4,3,-1,"Jumped too early, but overall looks great"
78,25-12-01 20-52-05 5968-00.15.22.660-00.15.27.083-seg17.mp4,Henrikas,fs-savanah,1,2,1,"landing really sketchy, just looks bad"
84,25-12-02 20-41-10 5974-00.06.17.804-00.06.22.170-seg19.mp4,Max,mizou,4,3,-1,"Great pose, the only downside its the landing a bit too early"
86,25-12-02 20-41-10 5974-00.07.11.832-00.07.16.068-seg24.mp4,Henrikas,bs-royale,3,2,-1,"Pose should be lower, balance looks ok. I just don't like the landing, it looks awkward. can't explain it."
87,25-12-02 20-41-10 5974-00.10.48.257-00.10.52.854-seg34.mp4,Vilius,top-soul,3,4,1,"Not full obstacle, loss of balance in the end. Landing seems forced, but not too unnatural"
88,25-12-02 20-41-10 5974-00.12.27.335-00.12.32.699-seg36.mp4,Henrikas,top-soul,3,4,1,"full obstacle, but clear imbalance throughout trick. Stylish overall though."
73,25-12-02 21-26-07 5982-00.07.22.658-00.07.26.954-seg5.mp4,Henrikas,fs-savanah,1,2,1,single foot landing
71,IMG_5540-00.02.01.080-00.02.07.798-seg5.mp4,Henrikas,soul,3,2,-1,"Just a bit too slow, otherwise great"
70,IMG_5677-00.03.16.617-00.03.22.224-seg8.mp4,Henrikas,mizou,3,2,-1,Form looks rly good. Way too short though
69,IMG_5678-00.00.29.551-00.00.34.335-seg1.mp4,Henrikas,soul,1,2,1,Short and i just don't like that landing. Looks awkward
68,IMG_5679-00.01.21.349-00.01.26.376-seg4.mp4,Henrikas,bs-royale,2,3,1,"Low body position, but short and slow."
92,IMG_5679-00.01.46.806-00.01.50.995-seg5.mp4,Henrikas,bs-royale,3,2,-1,"Way too short, but body position is great."
96,IMG_5682-00.02.24.967-00.02.30.080-seg03.mp4,Henrikas,ao-soul,3,2,-1,"slow & short, but i like the style"
98,IMG_5683-00.02.10.776-00.02.15.557-seg02.mp4,Henrikas,fs-savanah,3,2,-1,"Execution looks really stylish, just too slow"
99,IMG_5683-00.03.37.922-00.03.43.734-seg05.mp4,Henrikas,fs-savanah,3,2,-1,"Execution looks really stylish, just too slow"